credentials:
  api_key: ad4eb7c5bb22729b727074073f395127
  secret_key: 22004c0da2eb15d7d24358481c31540e

websocket:
  public_uri: wss://fapi.bitunix.com/public/
  private_uri: wss://fapi.bitunix.com/private/
  reconnect_interval: 5

http:
  uri_prefix: https://fapi.bitunix.com
